# Generated by Django 3.0.8 on 2020-07-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200723_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('count', models.IntegerField(max_length=20)),
                ('content', models.CharField(max_length=20000)),
            ],
        ),
    ]
